# Generated by Django 4.2.13 on 2024-07-02 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_reviewmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availabletimemodel',
            old_name='name',
            new_name='available_time',
        ),
    ]
